spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: vira-services

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:default-secret-key-change-in-production}
    expiration: 86400000  # 24 hours
    refresh-expiration: 604800000  # 7 days

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# API Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operationsSorter: method
    disable-swagger-default-url: true
  show-actuator: true 