server:
  port: ${PORT:8080}

spring:
  # Supabase PostgreSQL Database for Production (Permanent, No Expiration)
  datasource:
    url: ${SUPABASE_DATABASE_URL}
    username: ${SUPABASE_DATABASE_USERNAME}
    password: ${SUPABASE_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      # Supabase specific SSL configuration
      ssl-mode: require
  
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    # Supabase requires SSL connections
    url: ${SUPABASE_DATABASE_URL}

# CORS Configuration for Production
cors:
  allowed-origins:
    - ${FRONTEND_URL:https://your-frontend-domain.com}
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

# Logging for Production
logging:
  level:
    root: INFO
    com.vira: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Security Headers
server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: strict

# JWT Configuration for Production
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000  # 24 hours
    refresh-expiration: 604800000  # 7 days 